### ISSUE TITLE
Vedic signs are used in other scripts

### ISSUE THREAD

**Issue by Shreeshrii** [roozbehp/unicode-data#1]
Please see http://sanskritdocuments.org/doc_veda/puruSukta.html?lang=sa
as a sample of webpage for usage of vedic accents in sanskrit text transliterated in other Indian scripts.

Currently, not all language scripts fully support this. Even though it would be for a very niche audience, it would be helpful to have vedic swaras support for all Indian scripts.

**Comment by roozbehp** [comment]
Thanks. This is just my staging area for Unicode data files. The best way to make sure we track this properly is submitting photos or scans of published printed material in non-Devanagari scripts using the Vedic signs either here or directly to Unicode.

**Comment by Shreeshrii** [comment]
![2016-07-26 4](https://cloud.githubusercontent.com/assets/5095331/17134187/d4193024-5346-11e6-8c17-5057fa30578b.png)
![2016-07-26 1](https://cloud.githubusercontent.com/assets/5095331/17134186/d413fa6e-5346-11e6-9e14-bbf3b1cfcaed.png)

Malayalam Script
Source:
https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxndXJ1a3VsYW00dmVkYXN8Z3g6NjQ2MTZhMDg4YzkxNTI3MQ

https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxndXJ1a3VsYW00dmVkYXN8Z3g6Mzc5NDc3MGU2MTQwNmI0MA

**Comment by Shreeshrii** [comment]
Tamil

Source:
https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxndXJ1a3VsYW00dmVkYXN8Z3g6MTA5NmVhZjA3OGRhY2U1YQ

https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxndXJ1a3VsYW00dmVkYXN8Z3g6MjIwNTFjYzc0Y2I2NDFhZA

![2016-07-26](https://cloud.githubusercontent.com/assets/5095331/17134277/3f9c3544-5347-11e6-9648-b2f8ac86ac9f.png)

**Comment by Shreeshrii** [comment]
Telugu Script
Source:
http://vedageethafoundation.org/Books/Mahanyasam-telugu.pdf

![2016-07-26 5](https://cloud.githubusercontent.com/assets/5095331/17134349/939aa022-5347-11e6-9369-94e9d0ec5d87.png)

**Comment by Shreeshrii** [comment]
Kannada Script
Source:
http://www.prapatti.com/slokas/kannada/panchasuuktam.pdf

![2016-07-26 6](https://cloud.githubusercontent.com/assets/5095331/17134665/21d5f7dc-5349-11e6-812c-41325389eb7f.png)

**Comment by Shreeshrii** [comment]
Oriya/Odia Script
Source:
http://www.odia.org/sanskrit/laxmi_shreesuktam_odi.pdf

![2016-07-26 7](https://cloud.githubusercontent.com/assets/5095331/17134934/9e6f7c5e-534a-11e6-9b1b-f9634092ad08.png)

**Comment by sridatta1** [comment]
### Shukla-yajurvedic characters in bengali script
Here is attestation for 1CD5  VEDIC TONE YAJURVEDIC AGGRAVATED INDEPENDENT SVARITA, 1CD6  VEDIC TONE YAJURVEDIC INDEPENDENT SVARITA, 1CD8 VEDIC TONE CANDRA BELOW
![yajurved1](https://cloud.githubusercontent.com/assets/23263723/23071662/25c1e35c-f555-11e6-8163-982220154ac2.PNG)
![yajurved2](https://cloud.githubusercontent.com/assets/23263723/23071663/25c3abc4-f555-11e6-86b4-abc496a779e6.PNG)
![yajurved5](https://cloud.githubusercontent.com/assets/23263723/23071664/25cb258e-f555-11e6-8c39-6fb58e6a7506.PNG)
![yajurveda3](https://cloud.githubusercontent.com/assets/23263723/23071665/25d0a37e-f555-11e6-9cc5-069b9fa18d0e.PNG)
From
http://eap.bl.uk/database/overview_item.a4d?catId=187010;r=31647
http://eap.bl.uk/database/overview_item.a4d?catId=187012;r=13093
here latin w,L are used due to lack of proper glyphs

Similar characters are used in other scripts , but materials aren't available online.

**Comment by sridatta1** [comment]
1CE1  VEDIC TONE ATHARVAVEDIC INDEPENDENT SVARITA

![atharva](https://cloud.githubusercontent.com/assets/23263723/23072454/b903d18c-f557-11e6-9ab9-86f974664030.PNG)
![atharvaveda](https://cloud.githubusercontent.com/assets/23263723/23072455/b90c17d4-f557-11e6-9cdd-e3ee554f25da.PNG)
**source:**
http://eap.bl.uk/database/overview_item.a4d?catId=186923;r=17465

**Comment by sridatta1** [comment]
### Samavedic characters in Bengali
**attestations for 1CD0 and 1CD2** 

![samaveda](https://cloud.githubusercontent.com/assets/23263723/23073526/e5922a9c-f55b-11e6-96ba-353a2ae2b6c3.PNG)
![samaveda1](https://cloud.githubusercontent.com/assets/23263723/23073527/e598034a-f55b-11e6-9b17-f3d924000f1a.PNG)
 **source**
http://eap.bl.uk/database/overview_item.a4d?catId=187038;r=21411
Combining digits and letters have not yet been encoded in Bengali (also Kannada,Telugu etc.) scripts.

No attestation is provided for 1CD1 VEDIC TONE SHARA which indicates  _dīpta śruti_ ,since  _dīpta śruti_ is indicated by VEDIC TONE ATHARVAVEDIC INDEPENDENT SVARITA see[ L2/15-164 ](http://www.unicode.org/L2/L2015/15164-vedic-characters-editorial-updates.pdf
)

**Comment by sridatta1** [comment]
Vedic Anusvara in Bengali
Script extensions for 1CEA and 1CED
![anusvara](https://cloud.githubusercontent.com/assets/23263723/23092870/441f94f2-f5fa-11e6-8925-2475afb27fa0.PNG)
![samveda](https://cloud.githubusercontent.com/assets/23263723/23092871/4423f1b4-f5fa-11e6-8e3e-bab930357f66.PNG)
**source**
http://eap.bl.uk/database/overview_item.a4d?catId=187038;r=21411

**Comment by roozbehp** [comment]
Hi. I am closing this issue tracker and sending your feedback to Unicode. In the future, please use https://www.unicode.org/reporting.html to report issues.
