### ISSUE TITLE
Category of U+AA29 CHAM VOWEL SIGN AA

### ISSUE THREAD

**Issue by behdad** [roozbehp/unicode-data#6]
Even though U+AA29 CHAM VOWEL SIGN AA is called a vowel sign, it, in fact, is a vowel lengthener and can occur after a consonant (lengthening the inherent A vowel), or any other vowel.  As such, it should be recategorized as a vowel modifier, NOT a vowel (which it currently is) for Universal Shaping Engine purposes.  While we can carry this as an override in USE, it makes more sense to us that Unicode data files reflect this distinction.  I don't know if a new category is needed.

Andrew Glass suggested the same resolution in private communication with Ben Mitchell.

Ref. https://github.com/behdad/harfbuzz/issues/376

**Comment by roozbehp** [comment]
There is no category for a vowel modifier in Indic Syllabic Categories. The whole concept is hard to define, since quite a few characters cross the boundary between a vowel and a vowel modifier. For example, U+0D57 MALAYALAM AU LENGTH MARK acts very similar to what you're describing, and can be a vowel by itself or follow another vowel. I left myself a TODO at 5d81267e2e9734791d04eb8ba2420fb51758b1c7, but I'm not hopeful we can easily split the Vowel_Dependent class in two.

In the future, please use https://www.unicode.org/reporting.html for reporting issues.
